### ISSUE TITLE
七牛错误导致 还是mogodb没连上

### ISSUE THREAD

**Issue by xvinc** [mvpzx/elapse#13]
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
[ /^\/api\/v1\/user/,
  /^\/api\/v1\/article/,
  /^\/api\/v1\/classify/,
  /^\/api\/v1\/tag/ ]
未找到与 qiniu Controller 对应的 qiniu Model
Server is running at http://localhost:3000
C:\Users\Administrator\Desktop\elapse-master\server\node_modules\mongodb\lib\mongo_client.js:838
            throw err;
            ^

ReferenceError: err is not defined
    at NativeConnection.db.on (C:\Users\Administrator\Desktop\elapse-master\server\connection\mongodb.js:19:29)
    at emitOne (events.js:115:13)
    at NativeConnection.emit (events.js:210:7)
    at C:\Users\Administrator\Desktop\elapse-master\server\node_modules\mongoose\lib\connection.js:431:17
    at err (C:\Users\Administrator\Desktop\elapse-master\server\node_modules\mongodb\lib\utils.js:415:14)
    at executeCallback (C:\Users\Administrator\Desktop\elapse-master\server\node_modules\mongodb\lib\utils.js:404:25)
    at C:\Users\Administrator\Desktop\elapse-master\server\node_modules\mongodb\lib\mongo_client.js:272:21
    at connectCallback (C:\Users\Administrator\Desktop\elapse-master\server\node_modules\mongodb\lib\mongo_client.js:955:5)
    at C:\Users\Administrator\Desktop\elapse-master\server\node_modules\mongodb\lib\mongo_client.js:835:13
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mvpzx** [comment]
你应当修改 server/config中的 mongodb地址，这里的报错是没有定义 qiniumodel，但是没关系，所以应当是 mongodb 配置问题

**Comment by xvinc** [comment]
说明下nodejs版本，尽量与你环境版本一致

**Comment by mvpzx** [comment]
v9.4.0

**Comment by mvpzx** [comment]
可以看下 README

**Comment by mvpzx** [comment]
求start

**Comment by xvinc** [comment]
window 问题不少 我还是部署在linux上 哈哈 学习范本

**Comment by mvpzx** [comment]
建议使用 unix / Linux，安装 mongodb 都省力些，如果会 docker 的话，可以用 docker 搭环境，更加方便简洁

**Comment by xvinc** [comment]
服务器又用docker容器 你觉得合适吗？我感觉又造了个容器 尴尬

**Comment by mvpzx** [comment]
如果还是连不上，那可能就是你的 mongodb 没有设置 用户密码，那么你修改下 
```
const url = `mongodb://${config.user}:${config.pwd}@${config.host}:${config.port}/${config.name}`;

// 改成这样
const url = `mongodb://${config.host}:${config.port}/${config.name}`;
```
代码位置：server/connection/mongodb.js

如果是这个原因，那就打我脸了，我只能捂脸，逃～～

**Comment by mvpzx** [comment]
我已经修改了这部分连接地址判断，你可以拉一下代码

**Comment by xvinc** [comment]
感谢 ，我之前已经clone ,正在用nvm 搭linux环境

**Comment by mvpzx** [comment]
Happy coding!

**Comment by xvinc** [comment]
要注释 哈哈，七牛云限制域名 估计我就用不了了

**Comment by xvinc** [comment]
一直以为七牛云要收费 不敢用

**Comment by mvpzx** [comment]
可以注册下，有免费服务。

**Comment by mvpzx** [comment]
你给我看下你的代码
wx: kaivn07

**Comment by xvinc** [comment]
PS C:\Users\Administrator\Desktop\elapse-master\koa> node .\app.js
C:\Users\Administrator\Desktop\elapse-master\koa\router\index.js:4
  router.get('/', Controller.hello) // 注意是在controller编写的hello函数
                  ^

ReferenceError: Controller is not defined
    at module.exports.app (C:\Users\Administrator\Desktop\elapse-master\koa\router\index.js:4:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\elapse-master\koa\app.js:8:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

**Comment by mvpzx** [comment]
CMD 了解一下，（主要看一下：module.exports 和 require）

**Comment by xvinc** [comment]
我跟着你代码抄的
